import numpy as np
from PIL import Image

class ImagePool():
    def __init__(self, pool_size):
        self.pool_size = pool_size

        if self.pool_size > 0: # create an empty pool
            self.num_images = 0
            self.images = []

    def query(self, images):
        """
            Retrieve images from the pool.

            Args:
                images: A numpy array representing the latest images generated by the Generator

            Returns:
                pool_images: A numpy array containing images queried from the pool
        """
        if self.pool_size == 0: # do nothing if buffer size is 0
            return images
